-- Очистка турнирных данных без затрагивания таблицы servers.
-- Выполнять под пользователем с правами на TRUNCATE:
--   psql "$DATABASE_URL" -f scripts/truncate_tournament_data.sql
BEGIN;
  TRUNCATE TABLE player_stats RESTART IDENTITY CASCADE;
  TRUNCATE TABLE files RESTART IDENTITY CASCADE;
  TRUNCATE TABLE events_raw RESTART IDENTITY;
  TRUNCATE TABLE map_event_aggregates RESTART IDENTITY;
  TRUNCATE TABLE event_offsets RESTART IDENTITY;
  TRUNCATE TABLE maps RESTART IDENTITY CASCADE;
  TRUNCATE TABLE matches RESTART IDENTITY CASCADE;
  TRUNCATE TABLE players RESTART IDENTITY CASCADE;
  TRUNCATE TABLE teams RESTART IDENTITY CASCADE;
  TRUNCATE TABLE tournaments RESTART IDENTITY CASCADE;
  TRUNCATE TABLE audit_log RESTART IDENTITY;
  TRUNCATE TABLE bot_subscriptions RESTART IDENTITY;
COMMIT;
